title: zijie8247's Homepage
page-top-title: Zijie Wang
top-section-bg-text: Welcome to Zijie's Homepage!
home-subtitle: Zijie Wang&ensp;|&ensp;王子杰
copyright-text: '&copy; Zijie Wang 2025. All Rights Reserved.'
